pipeline {
       agent any
       stages {
           stage('Test') {
               steps {
                   echo "Downstream pipeline triggered at ${new Date()}"
               }
           }
       }
   }
